name: Build 
on: 
  push: 
    branches: 
      - main 

jobs: 
  build: 
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ub22", "ws16"]
    steps: 
      - name: Get the source
        uses: actions/checkout@v1

      - name: Use Node.JS 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Restore the dependencies 
        run: npm ci 

      - name: Build 
        run: npm run all    
