name: Test

on: 
  push: 
    branches: 
      - main 
  pull_request:
    branches:
      - main

jobs: 
  build: 
    name: Test 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ub22", "ws16"]

    steps: 

      - name: Get the source
        uses: actions/checkout@v1

      - name: Use Node.JS 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Create a release draft for a version tag 
        id: create-release-draft 
        uses: ./
        with: 
          repo-token: ${{ secrets.CM_GITHUB_TOKEN }}

      - name: Print the URL of the release draft (Linux)
        if: matrix.os == "ub22"
        run: echo ${{ steps.create-release-draft.outputs.release-url }}

      - name: Print the URL of the release draft (Windows) 
        if: matrix.os == "ws16"
        run: Write-Host "${{ steps.create-release-draft.outputs.release-url }}"
        shell: powershell
